# Default values for hello-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

metadata:
  app: web
  namespace: default
  name: web

image:
  repository: gcr.io/google-samples/hello-app:1.0
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.0.1"

nameOverride: ""
fullnameOverride: ""

deployment:
  maxSurge: 25%
  maxUnavailable: 25%
  type: RollingUpdate

ingres:
  ingressClassName: nginx
  name: example-ingress
  hosts: 
   - host: hello-world.info 

service:
  type: NodePort
  port: 8080
  nodePort: 30523
  clusterIP: 10.107.143.179

nodeSelector: 
  # example to me, that say to me if syntax is good for with functions 
  region: americas

tolerations: {}

affinity: {}

resources: 
  region: americas

podSecurityContext: {}