apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-12-29T09:25:34Z"
  labels:
    app: {{ .Values.metadata.app }} 
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  clusterIP: {{ .Values.service.clusterIP }}
  clusterIPs: {{ .Values.service.clusterIP }}
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: {{ .Values.service.nodePort }}
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.metadata.app }} 
  sessionAffinity: None
  type: {{ .Values.service.type }}