apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.ingress.hosts }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.metadata.name }}
            port:
              number: {{ .Values.service.port }}
        path: /
        pathType: Prefix
