name: 'Helm3 pipeline'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test:
    runs-on: 'ubuntu-latest'
    services:
      chartmuseum:
        image: ledu32/helloworld
        ports:
        - 8080:8080
        env:
          DEBUG: 1
          STORAGE: local
          STORAGE_LOCAL_ROOTDIR: /charts
          BASIC_AUTH_USER: admin
          BASIC_AUTH_PASS: test
        volumes:
        - /tmp:/charts

    steps:
    - uses: 'actions/checkout@v2'

    - name: 'Build docker image'
      run: 'docker build -t helm .'

    - name: Helm Push Action
      uses: Goodsmileduck/helm-push-action@v3


    - name: 'Test helm v3 push'
      uses: ./
      env:
        SOURCE_DIR: '.github/'
        CHART_FOLDER: 'chart'
        FORCE: 'True'
        CHARTMUSEUM_URL: 'http://locallhost:8080'
        CHARTMUSEUM_USER: 'admin'
        CHARTMUSEUM_PASSWORD: 'test'